### ISSUE TITLE
`fmove.accuracyChance` should be `cmove.accuracyChance`?

### ISSUE THREAD

**Issue by g2384** [WHIZENx/PokeGoBreeze#2]
Should `fmove.accuracyChance` be `cmove.accuracyChance` here?

https://github.com/WHIZENx/PokeGoBreeze/blob/81b932b84f2a90421110bf1991956bcc55c55e52/src/components/Calculate/Calculate.js#L543

**Comment by WHIZENx** [comment]
Ah yes, Thank for told me which this wrong. I will be fix it.
