### ISSUE TITLE
`calculateStatsBettlePure` vs `calculateStatsBettle`

### ISSUE THREAD

**Issue by g2384** [WHIZENx/PokeGoBreeze#3]
https://github.com/WHIZENx/PokeGoBreeze/blob/2b37c7025c8bdede36110d0858d97415ba265b84/src/components/Calculate/Calculate.js#L458

Hi, why doesn't `calculateStatsBettlePure` use math.floor(result*addition)? like the one used in `calculateStatsBettle`.

Plus, how about renaming `bettle` to `battle`?

**Comment by WHIZENx** [comment]
Thank for told this issue, because `calculateStatsBettle` use in old version and `calculateStatsBettlePure` use in new version. That function duplicated and should use `calculateStatsBettlePure` in new version.

I will remove old function `calculateStatsBettle` and rename it later.
