### ISSUE TITLE
Moves of mewtwo

### ISSUE THREAD

**Issue by g2384** [WHIZENx/PokeGoBreeze#4]
according to this page:
https://poke-go-breeze.vercel.app/pokemon/150

Mewtwo's best comb is Confusion + Psystrike[Elite].

However, this page doesn't show this comb on non-shadow Mewtwo.

Is this a display bug or Psystrike is only for shadow Mewtwo?

**Comment by WHIZENx** [comment]
> Is this a display bug or Psystrike is only for shadow Mewtwo?

This issue is display not correct in dps&tdo sheet page, I will be fix it later.

**Comment by WHIZENx** [comment]
@g2384 This issue was fixed, Please check in that page again.

Closing issue
Thank!

**Comment by WHIZENx** [comment]
@g2384 This issue was fixed, Please check in that page again. If still this comb not display, Tell me again.

Thank!

**Comment by g2384** [comment]
thank you, it's fixed now.
