### ISSUE TITLE
Missing elite tag on search-pokemon page

### ISSUE THREAD

**Issue by g2384** [WHIZENx/PokeGoBreeze#5]
I feel very sorry that I keep opening new issues.

It seems that elite tag sometimes doesn't display on https://poke-go-breeze.vercel.app/search-pokemon page.

For example, search "Kirlia", then go to "Best Pokémon Counter", and load all pokemons,

Gengar is the first option, seems correct, with `lick + shadow ball` comb. 

However, if you go to Gengar's page, https://poke-go-breeze.vercel.app/pokemon/94, `lick` is actually an elite move. It is not highlighted on the Kirlia's page.

---

BTW, this is a fantasitc project, and I really love what you've developed here.

**Comment by WHIZENx** [comment]
@g2384 This issue has been fixed.

Thank you for your interested my project!
